Workaround rubygems/bundler version mismatch on travis
The new trusty images on travis ship a new rubygems, without updating
bundler causing the install to fail with

```
NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing rspec-puppet (2.6.8), and Bundler cannot
continue.

Make sure that `gem install rspec-puppet -v '2.6.8'` succeeds before bundling.
The command "eval bundle install --without development --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 2 of 3.
```

Installing a newer bundler version fixes this.